CREATE TABLE [cocomoEstimation] (
  [estimationID] INTEGER NOT NULL PRIMARY KEY, 
  [nodeID] INT NOT NULL, 
  [EMType] TEXT(10),  
  [sumSF] DOUBLE,  
  [productEM] DOUBLE,  
  [SCEDValue] DOUBLE,  
  [PM] DOUBLE, 
  [devTime] DOUBLE, 
  [PREC] TEXT(2),    
  [FLEX] TEXT(2),    
  [RESL] TEXT(2), 
  [TEAM] TEXT(2),    
  [PMAT] TEXT(2),    
  [RELY] TEXT(2), 
  [DATA] TEXT(2),    
  [CPLX] TEXT(2),    
  [RUSE] TEXT(2), 
  [DOCU] TEXT(2),    
  [TIME] TEXT(2),    
  [STOR] TEXT(2),     
  [PVOL] TEXT(2),    
  [ACAP] TEXT(2),    
  [PCAP] TEXT(2), 
  [PCON] TEXT(2),    
  [APEX] TEXT(2),    
  [PLEX] TEXT(2), 
  [LTEX] TEXT(2),    
  [TOOL] TEXT(2),    
  [SITE] TEXT(2), 
  [SCED] TEXT(2),    
  [RCPX] TEXT(2),    
  [PDIF] TEXT(2),     
  [PERS] TEXT(2),    
  [PREX] TEXT(2),    
  [FCIL] TEXT(2)   
  );